const en = {
  signUp_heading:"SIGN UP",
  email:"Email",
  password:"Password",
  first_name:"First Name",
  last_name:"Last Name",
  login_button:"LOGIN",
  sign_up_button:"Create Account",
  forgot_password:"Forgot Password?",
  already_member:"Already Member",
  or:"or",
  sign_up_with:"Sign Up With",
  skip:"Skip",
  first_name_error:"First name field cannot be empty.",
  last_name_error:"Last name field cannot be empty.",
  email_error:"Email field cannot be empty.",
  password_error:"Password field cannot be empty.",
  invalid_email_title:"Invalid Email Address!",
  invalid_email_description:"User Exist",
  user_exist_title:"'User Exist'",
  user_exist_description:"This email address is already registered with us.",
  okay:"Okay",
  wrong_input:"Wrong Input!",
}

const de = {
  signUp_heading:"ANMELDEN", 
  email:"Email",
  password:"Passwort",
  first_name:"Vorname",
  last_name:"Nachname",
  login_button:"ANMELDUNG",
  sign_up_button:"Konto anlegen",
  forgot_password:"Passwort vergessen?",
  already_member:"Bereits Mitglied",
  or:"oder",
  sign_up_with:"Anmelden mit",
  skip:"Überspringen",
  first_name_error:"Das Feld Vorname darf nicht leer sein.",
  last_name_error:"Das Feld Vorname darf nicht leer sein.",
  email_error:"Das E-Mail-Feld darf nicht leer sein.",
  password_error:"Das Passwortfeld darf nicht leer sein.",
  invalid_email_title:"Ungültige E-Mail-Adresse!",
  invalid_email_description:"Benutzer existiert",
  user_exist_title:"Diese E-Mail-Adresse ist bereits bei uns registriert.",
  user_exist_description:"Benutzer existiert",
  okay:"Okay",
  wrong_input:"Falsche Eingabe!",  
}

export {en,de}