const en = {
  home:"Home",
  campaign:"Campaign",
  cart:"Cart",
  profile:"Profile",
  favorite:"Favorite",
  aboutUs:"About Human Relief",
  setting:"Settings",
  aboutApplication:"About Application",
  rateTheApplication:"Rate the Application",
  share:"Share",
  logout:"logout",
  login:"Login",
  sign_up:"Sign Up",
  my_account:"My Account",
  donation_history:"Donation History",
  about_app:"About App",
  support:"Support",
  notification:"Notification",
  favourites:"Favourites",
  report:"Report",
  help:"Help",
  order_cancel:"Order Cancel!",
  order_success:"Transaction Successful!",
  order_cancel_label:"Order \nCancel!",
  order_success_label:"Transaction \nSuccessful!",
  goto_home:"Go to Home",
  view_order:"View Transaction",
}

const de = {
  home:"Heim",
  campaign:"Kampagne",
  cart:"Wagen",
  profile:"Profil",
  favorite:"Favoritin",
  aboutUs:"Über Human Relief",
  setting:"Einstellung",
  aboutApplication:"Über Bewerbung",
  rateTheApplication:"Bewerten Sie uns",
  share:"Teilen",
  logout:"Ausloggen",
  login:"Einloggen",
  sign_up:"Anmeldung",
  my_account:"Mein Konto",
  donation_history:"Spendengeschichte",
  about_app:"Über App",
  support:"Die Unterstützung",
  notification:"Benachrichtigung",
  favourites:"Favoritinnen",
  favourites:"Favoritinnen",
  report:"Bericht",
  help:"Hilfe",
  order_cancel:"Bestellung stornieren!",
  order_success:"Bestellung erfolgreich!",
  order_cancel_label:"Bestellung \nstornieren!",
  order_success_label:"Bestellung \nerfolgreich!",
  goto_home:"Zur Startseite",
  view_order:"Bestellung ansehen",
}

export {en,de}